-- 检查knowledge表的实际结构
USE farmproject_db;

-- 查看表结构
DESCRIBE knowledge;

-- 查看所有字段
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    CHARACTER_MAXIMUM_LENGTH, 
    IS_NULLABLE, 
    COLUMN_DEFAULT,
    COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'farmproject_db' AND TABLE_NAME = 'knowledge'
ORDER BY ORDINAL_POSITION;

